#!/bin/bash

# this script is run on bootup. it runs through the several stages of installation
STAGE_PTR="/boot/RoPieee/.install_stage"



Partition_SD()
{
   cat << _EOF_ | fdisk /dev/mmcblk0
p
d
2
n
p
2
$(parted /dev/mmcblk0 -ms unit s p | grep '^2:' | sed 's/:/ /g' | sed 's/s//g' | awk '{ print $2 }')

n
p
w

_EOF_
}

Expand_SD()
{
   # Resize Filesystem to new partition size
   #resize2fs /dev/mmcblk0p2

   # for f2fs we can't resize a mounted fs, so we need to switch to rescue mode
   cat << _EOF_ > /tmp/bbbootstrap
umount /
mount /boot
resize.f2fs /dev/mmcblk0p2
sleep 1
echo 2 > /boot/RoPieee/.install_stage
systemctl reboot
_EOF_

   systemctl rescue
}

stage2()
{
   # we're done. this is business as usual
   echo " ** stage2"

   . /etc/ropieee.conf
   /sbin/shutdown -r $rp_reboottime
}

stage1()
{
   echo " ** stage1"

   # enable the web interface
   systemctl enable ropieee-web

   Expand_SD

   echo 2 > $STAGE_PTR
   reboot
}

stage0()
{
   echo " ** stage0"

   Partition_SD
   
   echo 1 > $STAGE_PTR
   reboot
}



echo "*** bootstrapping RoPieee ***"
BOOTSTRAP_STAGE=$( cat ${STAGE_PTR} )

stage${BOOTSTRAP_STAGE}

exit 0

