#!/bin/bash

# this script is run on bootup. it runs through the several stages of installation
STAGE_PTR="/boot/RoPieee/.install_stage"
LIB="/opt/RoPieee/lib"

# change to tty 2
chvt 2
systemctl stop getty@tty2
echo "*** Welcome to RoPieee! ***" > /dev/tty2
echo > /dev/tty2





log_to_screen()
{
   echo $1 > /dev/tty2
}

partition_disk()
{
   cat << _EOF_ | fdisk /dev/mmcblk0
p
d
2
n
p
2
$(parted /dev/mmcblk0 -ms unit s p | grep '^2:' | sed 's/:/ /g' | sed 's/s//g' | awk '{ print $2 }')

n
p
w

_EOF_
}

expand_fs()
{
   # Resize Filesystem to new partition size
   resize2fs /dev/mmcblk0p2

   ### BELOW IS F2FS


   # for f2fs we can't resize a mounted fs, so we need to switch to rescue mode
#   cat << _EOF_ > /tmp/bbbootstrap
#umount /
#mount /boot
#resize.f2fs /dev/mmcblk0p2
#sleep 1
#echo 2 > /boot/RoPieee/.install_stage
#journalctl > /boot/RoPieee/log/stage1.log
#systemctl reboot
#_EOF_

#   systemctl rescue
}

wait_for_timesync()
{
   loop=1
   while true
   do
      /boot/RoPieee/check_ntp_offset
      test $? -eq 0 && return
      sleep 1
      loop=$( expr $loop + 1 )
      if [ $loop -gt 30 ]
      then
         systemctl restart ntpdate
	 loop=1
      fi
   done
}

detect_touchscreen()
{
  if [ $( lsmod | grep -c rpi_ft5406 ) -gt 0 ] && [ $( cat /proc/cmdline | grep -c bcm2708_fb ) -gt 0 ]
  then
     return 0
  else
     return 1
  fi
}

stage3()
{
   # we're done. this is business as usual
   log_to_screen "... Entering stage 3. We're almost done ..."

   # just to be sure.
   rm -f /var/lib/pacman/db.lck

   # disable HDMI
   /opt/vc/bin/tvservice -o

   # make sure Roon logs to ram
   rm -rf /var/roon/RAATServer/Logs
   mkdir /tmp/raatserver_log
   ln -s /tmp/raatserver_log /var/roon/RAATServer/Logs

   rm -rf /var/roon/RoonBridge/Logs
   mkdir /tmp/roonbridge_log
   ln -s /tmp/roonbridge_log /var/roon/RoonBridge/Logs

   # wait for NTP
   log_to_screen "... Waiting for NTP synchronization ..."
   wait_for_timesync

   # is there something that needs rescueing?
   /boot/RoPieee/run_rescue_scripts

   # change led control
   systemctl stop ropieee1-led
   /boot/RoPieee/control_led running &

   . /etc/ropieee.conf
   shutdown -r $rp_reboottime

   log_to_screen "... We're ready. RoPieeee is RUNNING ..."
   echo " **** RoPieee RUNNING ****"

   # let's go to bed...
   while true
   do
      sleep 60
   done
}

stage2()
{
   # we're done with configuring storage.
   echo " **** RoPieee stage 2 ****"
   log_to_screen "... Entering stage (2/3) ..."
   log_to_screen "... Installing additional software. This can take a while ..."

   # install RoonBridge
   $LIB/install_roonbridge

   # and run the updates for the first time
   /opt/RoPieee/sbin/run-updates

   # let's see if we've got a touchscreen
   if detect_touchscreen
   then
      echo "Touchscreen detected!"
      log_to_screen "... Touchscreen detected ..."
      cat /etc/ropieee.conf |
      sed -e 's/^rp_touchscreen_detected=.*$/rp_touchscreen_detected=1/' > /tmp/ropieee.conf.$$
      cp /tmp/ropieee.conf.$$ /etc/ropieee.conf

      # increase gpu mem
      sed -i 's/gpu_mem=.*/gpu_mem=256/' /boot/config.txt

      log_to_screen "... Installing touchscreen software ..."
      $LIB/install_touchscreen
   fi

   # enable the web interface
   systemctl enable ropieee-web

   # enable automatic updates
   systemctl enable ropieee-update.timer

   # remove some leftovers
   rm /root/BOOTSTRAP
   rm /root/ropieee_repo

   echo 3 > $STAGE_PTR

   journalctl > /boot/RoPieee/log/stage2.log
   reboot
}

stage1()
{
   echo " **** RoPieee stage 1 ****"
   log_to_screen "... Entering stage (1/3) ..."
   log_to_screen "... Expanding filesystem. This can take a while ..."

   expand_fs

   echo 2 > $STAGE_PTR

   journalctl > /boot/RoPieee/log/stage1.log
   reboot
}

stage0()
{
   echo " **** RoPieee stage 0 ****"
   log_to_screen "... Entering stage (0/3) ..."
   log_to_screen "... Repartitioning disk. This can take a while ..."

   partition_disk
   
   echo 1 > $STAGE_PTR

   mkdir -p /boot/RoPieee/log

   journalctl > /boot/RoPieee/log/stage0.log
   reboot
}



echo "*** bootstrapping RoPieee ***"
BOOTSTRAP_STAGE=$( cat ${STAGE_PTR} )

stage${BOOTSTRAP_STAGE}

exit 0

