#!/bin/bash

# this script checks for updates

echo "*** RoPieee: checking for updates..."

i=1
while [ $i -le 5 ]
do
   echo "** run-updates: attempt $i **"
   pacman -Syu --needed <<< yes
   test $? -eq 0 && break
   i=$( expr $i + 1 )
done

exit $?
