#!/bin/bash

# this script checks for updates
LIB="/opt/RoPieee/lib"

echo "*** RoPieee: checking for updates..."

i=1
while [ $i -le 5 ]
do
   echo "** run-updates: attempt $i **"
   yes | pacman -Syu --needed
   test $? -eq 0 && break
   i=$( expr $i + 1 )
done

# if we're actually already running then we need to (re)set the timer
if systemctl is-enabled ropieee-update.timer
then
   $LIB/set_update_timer
fi

exit $?
