#!/bin/bash

FTP_USER="ropieee"
FTP_PASS='hb29dsOijF$*'
FTP_ADDR="vps.ten-berge.org/"

tmpdir=$( mktemp -d /tmp/feedback_XXXXX )

echo "gathering information in $tmpdir ..."

# add all logging
cp /boot/RoPieee/log/* $tmpdir
cp /opt/RoPieee/log/* $tmpdir

# and the current one
journalctl > $tmpdir/journal_current.log

# configuration
cp /etc/ropieee.conf $tmpdir
cp /etc/ropieee-remote.conf $tmpdir

# disk usage
df -lh > $tmpdir/df_lh.txt

# audio
aplay -l > $tmpdir/aplay_l.txt

# kernel
uname -a > $tmpdir/uname_a.txt

# processes
ps ax > $tmpdir/ps_ax.txt

# software
pacman -Q | grep ropieee > $tmpdir/pacman_q.txt

# repo
cp /etc/pacman.d/ropieee $tmpdir/pacman_ropieee.txt

echo "compressing information ..."
TARBALL="$( basename $tmpdir ).tar.bz2"
cd /tmp
tar jcf ./$TARBALL $( basename $tmpdir )

echo "sending it..."
wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u $TARBALL ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"

rm -rf $tmpdir
rm -f $TARBALL

exit 0

