#!/bin/bash

UNIQUE=$1

FTP_USER="ropieee"
FTP_PASS='hb29dsOijF$*'
FTP_ADDR="vps.ten-berge.org/"

if [ -z "$UNIQUE" ]
then
   tmpdir=$( mktemp -d /tmp/feedback_XXXXX )
else
   tmpdir=/tmp/feedback_${UNIQUE}
   mkdir $tmpdir
fi

test -n "$UNIQUE" && echo "sending feedback with id $UNIQUE"
echo "gathering information in $tmpdir ..."

# add all logging
cp /boot/RoPieee/log/* $tmpdir
cp /opt/RoPieee/log/* $tmpdir

# and the current one
journalctl > $tmpdir/journal_current.log

# configuration
cp /etc/ropieee.conf $tmpdir
cp /etc/ropieee-remote.conf $tmpdir

# disk usage
df -lhT > $tmpdir/df_lh.txt

# audio
aplay -l 2>&1 > $tmpdir/aplay_l.txt

# kernel
uname -a > $tmpdir/uname_a.txt

# processes
ps ax > $tmpdir/ps_ax.txt

# software
pacman -Q | grep ropieee >  $tmpdir/pacman_q.txt
pacman -Q | grep qt5     >> $tmpdir/pacman_q.txt

# repo
cp /etc/pacman.d/ropieee $tmpdir/pacman_ropieee.txt

echo "compressing information ..."
TARBALL="$( basename $tmpdir ).tar.bz2"
cd /tmp
tar jcf ./$TARBALL $( basename $tmpdir )

echo "sending it..."
wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u $TARBALL ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"

rm -rf $tmpdir
rm -f $TARBALL

exit 0

