#!/bin/bash

FTP_USER="ropieee"
FTP_PASS="v^8DMcaDc2A7"
FTP_ADDR="www.ropieee.org/sda1/ropieee/"

tmpdir=$( mktemp -d /tmp/feedback_XXXXX )

echo "gathering information in $tmpdir ..."

# add all logging
cp /boot/RoPieee/log/* $tmpdir
cp /opt/RoPieee/log/* $tmpdir

# and the current one
journalctl > $tmpdir/journal_current.log

# configuration
cp /etc/ropieee.conf $tmpdir
cp /etc/ropieee-remote.conf $tmpdir

# disk usage
df -lh > $tmpdir/df_lh.txt

# audio
aplay -l > $tmpdir/aplay_l.txt

# kernel
uname -a > $tmpdir/uname_a.txt

# processes
ps ax > $tmpdir/ps_ax.txt

echo "compressing information ..."
TARBALL="/tmp/$( basename $tmpdir ).tar.bz2"
tar jcf $TARBALL $tmpdir

echo "sending it..."
wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u $TARBALL ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"

rm -rf $tmpdir
rm -f $TARBALL

exit 0

