#!/bin/bash

# this script is run on SETUP.

CONF=/opt/RoPieee/conf

# setup initial config file
cat << _EOF_ > /etc/ropieee.conf
rp_hostname=ropieee
rp_reboottime=3:04
rp_audio=usb
_EOF_

# fix ssh access for root (permitRootlogin yes in sshd_config)
cp $CONF/sshd_config /etc/ssh

# fix modprobe for usb devices
cp $CONF/alsa-base.conf /etc/modprobe.d

# disable wifi
cp $CONF/99-blacklist.conf /etc/modprobe.d

# tune kernel params
cp $CONF/ropieee.conf /etc/sysctl.d

# everything in ram
cp $CONF/fstab /etc

# only volatile logging
cp $CONF/journald.conf /etc/systemd

# enable rescue mode
cp $CONF/rescue.service /etc/systemd/system

# setup bootstrap script
cat << _EOF_ > /etc/systemd/system/ropieee-bootstrap.service
[Unit]
Description=RoPieee-Bootstrap
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c '/boot/RoPieee/bootstrap'
StandardOutput=journal+console
SyslogIdentifier=ropieee

[Install]
WantedBy=multi-user.target
_EOF_

systemctl daemon-reload
systemctl enable ropieee-bootstrap.service
systemctl enable systemd-networkd-wait-online

# setup update script
cat << _EOF_ > /etc/systemd/system/ropieee-update.service
[Unit]
Description=RoPieee-Update
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c '/opt/RoPieee/sbin/run-updates'
StandardOutput=journal+console
SyslogIdentifier=ropieee-update

[Install]
WantedBy=multi-user.target
_EOF_

cat << _EOF_ > /etc/systemd/system/ropieee-update.timer
[Unit]
Description=Run ropieee-update on every boot

[Timer]
OnBootSec=15min

[Install]
WantedBy=timers.target
_EOF_

systemctl daemon-reload
systemctl enable ropieee-update.timer

# install RoonBridge
$CONF/roonbridge-installer-linuxarmv7hf.sh <<< y

