#!/bin/bash

# this script is run on SETUP.

CONF=/opt/RoPieee/conf

# fix ssh access for root (permitRootlogin yes in sshd_config)
cp $CONF/sshd_config /etc/ssh

# fix modprobe for usb devices
cp $CONF/alsa-base.conf /etc/modprobe.d

# disable wifi
cp $CONF/99-blacklist.conf /etc/modprobe.d

# tune kernel params
cp $CONF/ropieee.conf /etc/sysctl.d

# everything in ram
cp $CONF/fstab /etc

# only volatile logging
cp $CONF/journald.conf /etc/systemd

