#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

echo "blacklist brcmfmac" >  /etc/modprobe.d/99-ropieee-disable-wifi.conf
echo "blacklist cfg80211" >> /etc/modprobe.d/99-ropieee-disable-wifi.conf

rm -f /etc/systemd/network/wireless.network
systemctl daemon-reload
systemctl restart systemd-networkd
rmmod brcmfmac 2>/dev/null

exit 0 

