#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

# we only support wifi on the rpi3
test "$( /opt/RoPieee/lib/get_hardware_model )" != "rpi3" && exit 1 

# remove module blacklist
rm -f /etc/modprobe.d/99-ropieee-disable-wifi.conf

# create networkd configuration
cat << _EOF_ > /etc/systemd/network/wireless.network
[Match]
Name=wlan0

[Network]
DHCP=ipv4

[DHCP]
RouteMetric=20
_EOF_

systemctl daemon-reload

# insert modules
modprobe brcmfmac

# try to see if we can set the wireless-regdom
country_code=$( /opt/RoPieee/lib/get_country_code | tr [a-z] [A-Z] )
if [ -n "$country_code" ]
then
   if [ $( grep -c $country_code /etc/conf.d/wireless-regdom ) -gt 0 ]
   then
      echo "WIRELESS_REGDOM=${country_code}" >> /etc/conf.d/wireless-regdom
   fi
fi

# restart networking
systemctl restart systemd-networkd

exit 0

