#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

echo "options snd slots=snd-usb-audio" > /etc/modprobe.d/99-ropieee-enable-usb-audio.conf
rm -f /etc/modprobe.d/99-ropieee-disable-usb-audio.conf

exit 0 

