#!/bin/bash

# we need to retrieve the model from the CPU revision
MODEL="unknown"
REVISION_CODE=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}')

if [[ "$REVISION_CODE" = "a020a0" ||
      "$REVISION_CODE" = "a02082" ||
      "$REVISION_CODE" = "a22082" ||
      "$REVISION_CODE" = "a32082" ]]
then
   echo "detected Raspberry Pi model 3"
   MODEL="rpi3"
fi 
