#!/bin/bash

MODEL="unknown"

if [ -f /etc/ropieee-oem.conf ]
then
   MODEL=$( cat /etc/ropieee-oem.conf )
   echo "$MODEL"
   exit 0
fi

# we try to retrieve the model from the CPU revision
REVISION_CODE=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}')

if [[ "$REVISION_CODE" = "a020a0" ||
      "$REVISION_CODE" = "a02082" ||
      "$REVISION_CODE" = "a22082" ||
      "$REVISION_CODE" = "a32082" ||
      "$REVISION_CODE" = "a020d3" ]]
then
   MODEL="rpi3"
fi 

if [ $( uname -r ) = "3.10.38" ]
then
   MODEL="sparky"
fi

echo "$MODEL"
exit 0
