#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------


i=1
while [ $i -le 5 ] 
do
   echo "** install_touchscreen: attempt $i **"
   pacman -Syu  libglvnd ropieee-touchui <<< y
   test $? -eq 0 && break
   i=$( expr $i + 1 )
done

systemctl enable ropieee-remote
systemctl enable ropieee-touchui

