#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

URL="http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv7hf.sh"

echo "*** RoPieee: installing RoonBridge..."

i=1
while [ $i -le 3 ]
do
   echo "** attempt $i **"
   rm -f /tmp/roonbridge.sh
   wget -q -t 2 -T 30 -O /tmp/roonbridge.sh $URL
   test $? -eq 0 && break
   i=$( expr $i + 1 )
done

if [ $i -eq 4 ]
then
   echo "Error. Downloading RoonBridge failed!"
   exit 1
fi

chmod +x /tmp/roonbridge.sh
/tmp/roonbridge.sh <<< y

exit $? 

