#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

pacman -Syu libglvnd ropieee-touchui <<< y
systemctl enable ropieee-remote
#systemctl enable ropieee-touchui

