#!/bin/bash
# $RP_BEGIN_HEADER$ --------------------------------------------
#
# Copyright (C) 2017 RoPieee
#
# $RP_END_HEADER$ ----------------------------------------------

. /etc/ropieee.conf

if [ "${rp_auto_update}" = "daily" ]
then
   trigger_date=$( date '+%F %T' -d "+1 day" )
   cat << _EOF_ > /etc/systemd/system/ropieee-update.timer.d/ropieee-update-override.conf
[Timer]
OnCalendar=${trigger_date}
_EOF_
elif [ "${rp_auto_update}" = "weekly" ]
then
   trigger_date=$( date '+%F %T' -d "+1 week" )
   cat << _EOF_ > /etc/systemd/system/ropieee-update.timer.d/ropieee-update-override.conf
[Timer]
OnCalendar=${trigger_date}
_EOF_
elif [ "${rp_auto_update}" = "monthly" ]
then
   trigger_date=$( date '+%F %T' -d "+1 month" )
   cat << _EOF_ > /etc/systemd/system/ropieee-update.timer.d/ropieee-update-override.conf
[Timer]
OnCalendar=${trigger_date}
_EOF_
elif [ "${rp_auto_update}" = "manual" -o "${rp_auto_update}" = "on_boot" ]
then
   systemctl disable ropieee-update.timer
   systemctl stop ropieee-update.timer
fi

if [ "${rp_auto_update}" != "manual" -a "${rp_auto_update}" != "on_boot" ]
then
   systemctl daemon-reload
   systemctl enable ropieee-update.timer
   systemctl restart ropieee-update.timer
fi	

exit 0
